In [104]:
import pandas as pd

In [105]:
d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000],
'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'],
'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}

In [106]:
df = pd.DataFrame(data = d)
df['city'].unique()

array(['Tampa', 'Orlando', 'Jacksonville', 'Miami'], dtype=object)

In [107]:
df.head()

     sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small

In [108]:
from sklearn.preprocessing import OneHotEncoder

In [109]:
one = OneHotEncoder(handle_unknown = 'ignore', sparse_output=False)

In [110]:
onehot = one.fit_transform(df[['city']])
columns = one.get_feature_names_out(['city'])

In [111]:

onehot_df = (pd.DataFrame(onehot, columns = columns))
onehot_df.head()

   city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0                0.0         0.0           0.0         1.0
1                0.0         0.0           0.0         1.0
2                0.0         0.0           1.0         0.0
3                1.0         0.0           0.0         0.0
4                0.0         1.0           0.0         0.0

In [112]:
df = pd.concat([df , onehot_df], axis = 1).drop(columns=['city'])
df

      sales    size  city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0    100000   Small                0.0         0.0           0.0         1.0
1    222000  Medium                0.0         0.0           0.0         1.0
2   1000000   Large                0.0         0.0           1.0         0.0
3    522000   Large                1.0         0.0           0.0         0.0
4    111111   Small                0.0         1.0           0.0         0.0
5    222222  Medium                1.0         0.0           0.0         0.0
6   1111111   Large                0.0         1.0           0.0         0.0
7     20000   Small                0.0         1.0           0.0         0.0
8     75000  Medium                0.0         0.0           1.0         0.0
9     90000  Medium                0.0         0.0           1.0         0.0
10  1000000  Medium                0.0         0.0           1.0         0.0
11    10000   Small                0.0         0.0           1.0         0.0